// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: mic_room.proto
package com.zq.live.proto.MicRoom;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class MChangeRoomNameMsg extends Message<MChangeRoomNameMsg, MChangeRoomNameMsg.Builder> {
  public static final ProtoAdapter<MChangeRoomNameMsg> ADAPTER = new ProtoAdapter_MChangeRoomNameMsg();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NEWROOMNAME = "";

  /**
   * 房间名称
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  private final String newRoomName;

  public MChangeRoomNameMsg(String newRoomName) {
    this(newRoomName, ByteString.EMPTY);
  }

  public MChangeRoomNameMsg(String newRoomName, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.newRoomName = newRoomName;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.newRoomName = newRoomName;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MChangeRoomNameMsg)) return false;
    MChangeRoomNameMsg o = (MChangeRoomNameMsg) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(newRoomName, o.newRoomName);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (newRoomName != null ? newRoomName.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (newRoomName != null) builder.append(", newRoomName=").append(newRoomName);
    return builder.replace(0, 2, "MChangeRoomNameMsg{").append('}').toString();
  }

  public byte[] toByteArray() {
    return MChangeRoomNameMsg.ADAPTER.encode(this);
  }

  public static final MChangeRoomNameMsg parseFrom(byte[] data) throws IOException {
    MChangeRoomNameMsg c = null;
       c = MChangeRoomNameMsg.ADAPTER.decode(data);
    return c;
  }

  /**
   * 房间名称
   */
  public String getNewRoomName() {
    if(newRoomName==null){
        return DEFAULT_NEWROOMNAME;
    }
    return newRoomName;
  }

  /**
   * 房间名称
   */
  public boolean hasNewRoomName() {
    return newRoomName!=null;
  }

  public static final class Builder extends Message.Builder<MChangeRoomNameMsg, Builder> {
    private String newRoomName;

    public Builder() {
    }

    /**
     * 房间名称
     */
    public Builder setNewRoomName(String newRoomName) {
      this.newRoomName = newRoomName;
      return this;
    }

    @Override
    public MChangeRoomNameMsg build() {
      return new MChangeRoomNameMsg(newRoomName, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MChangeRoomNameMsg extends ProtoAdapter<MChangeRoomNameMsg> {
    public ProtoAdapter_MChangeRoomNameMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, MChangeRoomNameMsg.class);
    }

    @Override
    public int encodedSize(MChangeRoomNameMsg value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.newRoomName)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, MChangeRoomNameMsg value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.newRoomName);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MChangeRoomNameMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setNewRoomName(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public MChangeRoomNameMsg redact(MChangeRoomNameMsg value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
