//
// Created by 昝晓飞 on 16/9/14.
//

#ifndef KSYSTREAMERANDROID_STRING_CONTANTS_H
#define KSYSTREAMERANDROID_STRING_CONTANTS_H

#define LOG_ACCESS_KEY_INDEX 0
#define LOG_SECRET_KEY_INDEX 1
#define COUNT_ACCESS_KEY_INDEX 2
#define COUNT_SECRET_KEY_INDEX 3

#define LOG_ACCESS_KEY "D8uDWZ88ZKUCPu0KRJkR"
#define LOG_SECRET_KEY "2tueIxI3wqxo6IvVU9/Wn+h8RKNNBrxzk/vdmWSD"
#define COUNT_ACCESS_KEY "D8uDWZ88ZKW48/eZHmRm"
#define COUNT_SECRET_KEY "QtL2SMqgGy15m8WdhJx/X2/cnhMhCWGzS/KPY8z6"

#endif //KSYSTREAMERANDROID_STRING_CONTANTS_H
