// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: User.proto
package com.wali.live.proto.User;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 获取自己的信息
 * cmd:zhibo.user.getowninfo
 */
public final class GetOwnInfoReq extends Message<GetOwnInfoReq, GetOwnInfoReq.Builder> {
  public static final ProtoAdapter<GetOwnInfoReq> ADAPTER = new ProtoAdapter_GetOwnInfoReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ZUID = 0L;

  public static final Boolean DEFAULT_GETLIVEINFO = true;

  public static final Boolean DEFAULT_GETGCOININFO = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long zuid;

  /**
   * 是否拉取直播回放数、直播URL、直播roomid等直播房间信息，在一些用不到房间信息的调用入口请传false
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean getLiveInfo;

  /**
   * 是否拉取金币信息,默认fals
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean getGcoinInfo;

  public GetOwnInfoReq(Long zuid, Boolean getLiveInfo, Boolean getGcoinInfo) {
    this(zuid, getLiveInfo, getGcoinInfo, ByteString.EMPTY);
  }

  public GetOwnInfoReq(Long zuid, Boolean getLiveInfo, Boolean getGcoinInfo,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.zuid = zuid;
    this.getLiveInfo = getLiveInfo;
    this.getGcoinInfo = getGcoinInfo;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.zuid = zuid;
    builder.getLiveInfo = getLiveInfo;
    builder.getGcoinInfo = getGcoinInfo;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetOwnInfoReq)) return false;
    GetOwnInfoReq o = (GetOwnInfoReq) other;
    return unknownFields().equals(o.unknownFields())
        && zuid.equals(o.zuid)
        && Internal.equals(getLiveInfo, o.getLiveInfo)
        && Internal.equals(getGcoinInfo, o.getGcoinInfo);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + zuid.hashCode();
      result = result * 37 + (getLiveInfo != null ? getLiveInfo.hashCode() : 0);
      result = result * 37 + (getGcoinInfo != null ? getGcoinInfo.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", zuid=").append(zuid);
    if (getLiveInfo != null) builder.append(", getLiveInfo=").append(getLiveInfo);
    if (getGcoinInfo != null) builder.append(", getGcoinInfo=").append(getGcoinInfo);
    return builder.replace(0, 2, "GetOwnInfoReq{").append('}').toString();
  }

  public byte[] toByteArray() {
    return GetOwnInfoReq.ADAPTER.encode(this);
  }

  public static final class Builder extends Message.Builder<GetOwnInfoReq, Builder> {
    public Long zuid;

    public Boolean getLiveInfo;

    public Boolean getGcoinInfo;

    public Builder() {
    }

    public Builder setZuid(Long zuid) {
      this.zuid = zuid;
      return this;
    }

    /**
     * 是否拉取直播回放数、直播URL、直播roomid等直播房间信息，在一些用不到房间信息的调用入口请传false
     */
    public Builder setGetLiveInfo(Boolean getLiveInfo) {
      this.getLiveInfo = getLiveInfo;
      return this;
    }

    /**
     * 是否拉取金币信息,默认fals
     */
    public Builder setGetGcoinInfo(Boolean getGcoinInfo) {
      this.getGcoinInfo = getGcoinInfo;
      return this;
    }

    @Override
    public GetOwnInfoReq build() {
      if (zuid == null) {
        throw Internal.missingRequiredFields(zuid, "zuid");
      }
      return new GetOwnInfoReq(zuid, getLiveInfo, getGcoinInfo, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetOwnInfoReq extends ProtoAdapter<GetOwnInfoReq> {
    public ProtoAdapter_GetOwnInfoReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetOwnInfoReq.class);
    }

    @Override
    public int encodedSize(GetOwnInfoReq value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.zuid)
          + ProtoAdapter.BOOL.encodedSizeWithTag(2, value.getLiveInfo)
          + ProtoAdapter.BOOL.encodedSizeWithTag(3, value.getGcoinInfo)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetOwnInfoReq value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.zuid);
      ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.getLiveInfo);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.getGcoinInfo);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetOwnInfoReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setZuid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.setGetLiveInfo(ProtoAdapter.BOOL.decode(reader)); break;
          case 3: builder.setGetGcoinInfo(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetOwnInfoReq redact(GetOwnInfoReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
