// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: mic_room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum EMRoundOverReason implements WireEnum {
  /**
   * 未知
   */
  MROR_UNKNOWN(0),

  /**
   * 上个轮次结束
   */
  MROR_ROUND_NORMAL_OVER(1),

  /**
   * 当前玩家退出
   */
  MROR_IN_ROUND_PLAYER_EXIT(2),

  /**
   * 自己放弃演唱
   */
  MROR_SELF_GIVE_UP(3),

  /**
   * 合唱成功
   */
  MROR_CHO_SUCCESS(4),

  /**
   * 合唱失败
   */
  MROR_CHO_FAILED(5);

  public static final ProtoAdapter<EMRoundOverReason> ADAPTER = new ProtoAdapter_EMRoundOverReason();

  private final int value;

  EMRoundOverReason(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static EMRoundOverReason fromValue(int value) {
    switch (value) {
      case 0: return MROR_UNKNOWN;
      case 1: return MROR_ROUND_NORMAL_OVER;
      case 2: return MROR_IN_ROUND_PLAYER_EXIT;
      case 3: return MROR_SELF_GIVE_UP;
      case 4: return MROR_CHO_SUCCESS;
      case 5: return MROR_CHO_FAILED;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final class Builder {
    public EMRoundOverReason build() {
      return MROR_UNKNOWN;
    }
  }

  private static final class ProtoAdapter_EMRoundOverReason extends EnumAdapter<EMRoundOverReason> {
    ProtoAdapter_EMRoundOverReason() {
      super(EMRoundOverReason.class);
    }

    @Override
    protected EMRoundOverReason fromValue(int value) {
      return EMRoundOverReason.fromValue(value);
    }
  }
}
