// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: mic_room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class MGameConfig extends Message<MGameConfig, MGameConfig.Builder> {
  public static final ProtoAdapter<MGameConfig> ADAPTER = new ProtoAdapter_MGameConfig();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_MAXUSERCNT = 0;

  /**
   * 最大用户数（座位数）
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  private final Integer maxUserCnt;

  public MGameConfig(Integer maxUserCnt) {
    this(maxUserCnt, ByteString.EMPTY);
  }

  public MGameConfig(Integer maxUserCnt, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.maxUserCnt = maxUserCnt;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.maxUserCnt = maxUserCnt;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MGameConfig)) return false;
    MGameConfig o = (MGameConfig) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(maxUserCnt, o.maxUserCnt);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (maxUserCnt != null ? maxUserCnt.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (maxUserCnt != null) builder.append(", maxUserCnt=").append(maxUserCnt);
    return builder.replace(0, 2, "MGameConfig{").append('}').toString();
  }

  public byte[] toByteArray() {
    return MGameConfig.ADAPTER.encode(this);
  }

  public static final MGameConfig parseFrom(byte[] data) throws IOException {
    MGameConfig c = null;
       c = MGameConfig.ADAPTER.decode(data);
    return c;
  }

  /**
   * 最大用户数（座位数）
   */
  public Integer getMaxUserCnt() {
    if(maxUserCnt==null){
        return DEFAULT_MAXUSERCNT;
    }
    return maxUserCnt;
  }

  /**
   * 最大用户数（座位数）
   */
  public boolean hasMaxUserCnt() {
    return maxUserCnt!=null;
  }

  public static final class Builder extends Message.Builder<MGameConfig, Builder> {
    private Integer maxUserCnt;

    public Builder() {
    }

    /**
     * 最大用户数（座位数）
     */
    public Builder setMaxUserCnt(Integer maxUserCnt) {
      this.maxUserCnt = maxUserCnt;
      return this;
    }

    @Override
    public MGameConfig build() {
      return new MGameConfig(maxUserCnt, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MGameConfig extends ProtoAdapter<MGameConfig> {
    public ProtoAdapter_MGameConfig() {
      super(FieldEncoding.LENGTH_DELIMITED, MGameConfig.class);
    }

    @Override
    public int encodedSize(MGameConfig value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.maxUserCnt)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, MGameConfig value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.maxUserCnt);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MGameConfig decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setMaxUserCnt(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public MGameConfig redact(MGameConfig value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
