// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class QRoundOverMsg extends Message<QRoundOverMsg, QRoundOverMsg.Builder> {
  public static final ProtoAdapter<QRoundOverMsg> ADAPTER = new ProtoAdapter_QRoundOverMsg();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ROUNDOVERTIMEMS = 0L;

  public static final Integer DEFAULT_EXITUSERID = 0;

  public static final EQRoundOverReason DEFAULT_OVERREASON = EQRoundOverReason.ROR_UNKNOWN;

  public static final EQRoundResultType DEFAULT_RESULTTYPE = EQRoundResultType.ROT_UNKNOWN;

  /**
   * 本轮次结束的毫秒时间戳
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64"
  )
  public final Long roundOverTimeMs;

  /**
   * 退出用户的ID
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer exitUserID;

  /**
   * 切换轮次原因
   */
  @WireField(
      tag = 3,
      adapter = "com.zq.live.proto.Room.EQRoundOverReason#ADAPTER"
  )
  public final EQRoundOverReason overReason;

  /**
   * 演唱结果信息
   */
  @WireField(
      tag = 4,
      adapter = "com.zq.live.proto.Room.EQRoundResultType#ADAPTER"
  )
  public final EQRoundResultType resultType;

  /**
   * 下个轮次信息
   */
  @WireField(
      tag = 5,
      adapter = "com.zq.live.proto.Room.QRoundInfo#ADAPTER"
  )
  public final QRoundInfo nextRound;

  public QRoundOverMsg(Long roundOverTimeMs, Integer exitUserID, EQRoundOverReason overReason,
      EQRoundResultType resultType, QRoundInfo nextRound) {
    this(roundOverTimeMs, exitUserID, overReason, resultType, nextRound, ByteString.EMPTY);
  }

  public QRoundOverMsg(Long roundOverTimeMs, Integer exitUserID, EQRoundOverReason overReason,
      EQRoundResultType resultType, QRoundInfo nextRound, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roundOverTimeMs = roundOverTimeMs;
    this.exitUserID = exitUserID;
    this.overReason = overReason;
    this.resultType = resultType;
    this.nextRound = nextRound;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roundOverTimeMs = roundOverTimeMs;
    builder.exitUserID = exitUserID;
    builder.overReason = overReason;
    builder.resultType = resultType;
    builder.nextRound = nextRound;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof QRoundOverMsg)) return false;
    QRoundOverMsg o = (QRoundOverMsg) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(roundOverTimeMs, o.roundOverTimeMs)
        && Internal.equals(exitUserID, o.exitUserID)
        && Internal.equals(overReason, o.overReason)
        && Internal.equals(resultType, o.resultType)
        && Internal.equals(nextRound, o.nextRound);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (roundOverTimeMs != null ? roundOverTimeMs.hashCode() : 0);
      result = result * 37 + (exitUserID != null ? exitUserID.hashCode() : 0);
      result = result * 37 + (overReason != null ? overReason.hashCode() : 0);
      result = result * 37 + (resultType != null ? resultType.hashCode() : 0);
      result = result * 37 + (nextRound != null ? nextRound.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (roundOverTimeMs != null) builder.append(", roundOverTimeMs=").append(roundOverTimeMs);
    if (exitUserID != null) builder.append(", exitUserID=").append(exitUserID);
    if (overReason != null) builder.append(", overReason=").append(overReason);
    if (resultType != null) builder.append(", resultType=").append(resultType);
    if (nextRound != null) builder.append(", nextRound=").append(nextRound);
    return builder.replace(0, 2, "QRoundOverMsg{").append('}').toString();
  }

  public byte[] toByteArray() {
    return QRoundOverMsg.ADAPTER.encode(this);
  }

  public static final QRoundOverMsg parseFrom(byte[] data) throws IOException {
    QRoundOverMsg c = null;
       c = QRoundOverMsg.ADAPTER.decode(data);
    return c;
  }

  /**
   * 本轮次结束的毫秒时间戳
   */
  public Long getRoundOverTimeMs() {
    if(roundOverTimeMs==null){
        return DEFAULT_ROUNDOVERTIMEMS;
    }
    return roundOverTimeMs;
  }

  /**
   * 退出用户的ID
   */
  public Integer getExitUserID() {
    if(exitUserID==null){
        return DEFAULT_EXITUSERID;
    }
    return exitUserID;
  }

  /**
   * 切换轮次原因
   */
  public EQRoundOverReason getOverReason() {
    if(overReason==null){
        return new EQRoundOverReason.Builder().build();
    }
    return overReason;
  }

  /**
   * 演唱结果信息
   */
  public EQRoundResultType getResultType() {
    if(resultType==null){
        return new EQRoundResultType.Builder().build();
    }
    return resultType;
  }

  /**
   * 下个轮次信息
   */
  public QRoundInfo getNextRound() {
    if(nextRound==null){
        return new QRoundInfo.Builder().build();
    }
    return nextRound;
  }

  /**
   * 本轮次结束的毫秒时间戳
   */
  public boolean hasRoundOverTimeMs() {
    return roundOverTimeMs!=null;
  }

  /**
   * 退出用户的ID
   */
  public boolean hasExitUserID() {
    return exitUserID!=null;
  }

  /**
   * 切换轮次原因
   */
  public boolean hasOverReason() {
    return overReason!=null;
  }

  /**
   * 演唱结果信息
   */
  public boolean hasResultType() {
    return resultType!=null;
  }

  /**
   * 下个轮次信息
   */
  public boolean hasNextRound() {
    return nextRound!=null;
  }

  public static final class Builder extends Message.Builder<QRoundOverMsg, Builder> {
    public Long roundOverTimeMs;

    public Integer exitUserID;

    public EQRoundOverReason overReason;

    public EQRoundResultType resultType;

    public QRoundInfo nextRound;

    public Builder() {
    }

    /**
     * 本轮次结束的毫秒时间戳
     */
    public Builder setRoundOverTimeMs(Long roundOverTimeMs) {
      this.roundOverTimeMs = roundOverTimeMs;
      return this;
    }

    /**
     * 退出用户的ID
     */
    public Builder setExitUserID(Integer exitUserID) {
      this.exitUserID = exitUserID;
      return this;
    }

    /**
     * 切换轮次原因
     */
    public Builder setOverReason(EQRoundOverReason overReason) {
      this.overReason = overReason;
      return this;
    }

    /**
     * 演唱结果信息
     */
    public Builder setResultType(EQRoundResultType resultType) {
      this.resultType = resultType;
      return this;
    }

    /**
     * 下个轮次信息
     */
    public Builder setNextRound(QRoundInfo nextRound) {
      this.nextRound = nextRound;
      return this;
    }

    @Override
    public QRoundOverMsg build() {
      return new QRoundOverMsg(roundOverTimeMs, exitUserID, overReason, resultType, nextRound, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_QRoundOverMsg extends ProtoAdapter<QRoundOverMsg> {
    public ProtoAdapter_QRoundOverMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, QRoundOverMsg.class);
    }

    @Override
    public int encodedSize(QRoundOverMsg value) {
      return ProtoAdapter.SINT64.encodedSizeWithTag(1, value.roundOverTimeMs)
          + ProtoAdapter.UINT32.encodedSizeWithTag(2, value.exitUserID)
          + EQRoundOverReason.ADAPTER.encodedSizeWithTag(3, value.overReason)
          + EQRoundResultType.ADAPTER.encodedSizeWithTag(4, value.resultType)
          + QRoundInfo.ADAPTER.encodedSizeWithTag(5, value.nextRound)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, QRoundOverMsg value) throws IOException {
      ProtoAdapter.SINT64.encodeWithTag(writer, 1, value.roundOverTimeMs);
      ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.exitUserID);
      EQRoundOverReason.ADAPTER.encodeWithTag(writer, 3, value.overReason);
      EQRoundResultType.ADAPTER.encodeWithTag(writer, 4, value.resultType);
      QRoundInfo.ADAPTER.encodeWithTag(writer, 5, value.nextRound);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public QRoundOverMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setRoundOverTimeMs(ProtoAdapter.SINT64.decode(reader)); break;
          case 2: builder.setExitUserID(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: {
            try {
              builder.setOverReason(EQRoundOverReason.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 4: {
            try {
              builder.setResultType(EQRoundResultType.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 5: builder.setNextRound(QRoundInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public QRoundOverMsg redact(QRoundOverMsg value) {
      Builder builder = value.newBuilder();
      if (builder.nextRound != null) builder.nextRound = QRoundInfo.ADAPTER.redact(builder.nextRound);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
