// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum SpecialEmojiMsgType implements WireEnum {
  SP_EMOJI_TYPE_UNKNOWN(0),

  /**
   * 喜欢
   */
  SP_EMOJI_TYPE_LIKE(1),

  /**
   * 不喜欢
   */
  SP_EMOJI_TYPE_UNLIKE(2);

  public static final ProtoAdapter<SpecialEmojiMsgType> ADAPTER = new ProtoAdapter_SpecialEmojiMsgType();

  private final int value;

  SpecialEmojiMsgType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static SpecialEmojiMsgType fromValue(int value) {
    switch (value) {
      case 0: return SP_EMOJI_TYPE_UNKNOWN;
      case 1: return SP_EMOJI_TYPE_LIKE;
      case 2: return SP_EMOJI_TYPE_UNLIKE;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final class Builder {
    public SpecialEmojiMsgType build() {
      return SP_EMOJI_TYPE_UNKNOWN;
    }
  }

  private static final class ProtoAdapter_SpecialEmojiMsgType extends EnumAdapter<SpecialEmojiMsgType> {
    ProtoAdapter_SpecialEmojiMsgType() {
      super(SpecialEmojiMsgType.class);
    }

    @Override
    protected SpecialEmojiMsgType fromValue(int value) {
      return SpecialEmojiMsgType.fromValue(value);
    }
  }
}
