// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ERoomMsgType 房间消息类型
 */
public enum ERoomMsgType implements WireEnum {
  /**
   * 未知消息
   */
  RM_UNKNOWN(0),

  /**
   * 普通评论消息
   */
  RM_COMMENT(10),

  /**
   * 特殊表情消息
   */
  RM_SPECIAL_EMOJI(11),

  /**
   * 动态表情消息
   */
  RM_DYNAMIC_EMOJI(12),

  /**
   * 加入游戏指令消息
   */
  RM_JOIN_ACTION(100),

  /**
   * 加入游戏通知消息
   */
  RM_JOIN_NOTICE(101),

  /**
   * 准备游戏通知消息
   */
  RM_READY_NOTICE(102),

  /**
   * 游戏轮次结束通知消息
   */
  RM_ROUND_OVER(103),

  /**
   * 轮次和游戏结束通知消息
   */
  RM_ROUND_AND_GAME_OVER(104),

  /**
   * app进程后台切换通知
   */
  RM_APP_SWAP(105),

  /**
   * 状态同步
   */
  RM_SYNC_STATUS(106),

  /**
   * 在开始游戏前退出
   */
  RM_EXIT_GAME_BEFORE_PLAY(107),

  /**
   * 在完成游戏后退出
   */
  RM_EXIT_GAME_AFTER_PLAY(108),

  /**
   * 在游戏中,但不再round时退出
   */
  RM_EXIT_GAME_OUT_ROUND(109);

  public static final ProtoAdapter<ERoomMsgType> ADAPTER = new ProtoAdapter_ERoomMsgType();

  private final int value;

  ERoomMsgType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ERoomMsgType fromValue(int value) {
    switch (value) {
      case 0: return RM_UNKNOWN;
      case 10: return RM_COMMENT;
      case 11: return RM_SPECIAL_EMOJI;
      case 12: return RM_DYNAMIC_EMOJI;
      case 100: return RM_JOIN_ACTION;
      case 101: return RM_JOIN_NOTICE;
      case 102: return RM_READY_NOTICE;
      case 103: return RM_ROUND_OVER;
      case 104: return RM_ROUND_AND_GAME_OVER;
      case 105: return RM_APP_SWAP;
      case 106: return RM_SYNC_STATUS;
      case 107: return RM_EXIT_GAME_BEFORE_PLAY;
      case 108: return RM_EXIT_GAME_AFTER_PLAY;
      case 109: return RM_EXIT_GAME_OUT_ROUND;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final class Builder {
    public ERoomMsgType build() {
      return RM_UNKNOWN;
    }
  }

  private static final class ProtoAdapter_ERoomMsgType extends EnumAdapter<ERoomMsgType> {
    ProtoAdapter_ERoomMsgType() {
      super(ERoomMsgType.class);
    }

    @Override
    protected ERoomMsgType fromValue(int value) {
      return ERoomMsgType.fromValue(value);
    }
  }
}
