// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Room.proto
package com.zq.live.proto.Room;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GameInfo extends Message<GameInfo, GameInfo.Builder> {
  public static final ProtoAdapter<GameInfo> ADAPTER = new ProtoAdapter_GameInfo();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_STARTTIMEMS = 0L;

  public static final Long DEFAULT_STARTPASSEDMS = 0L;

  /**
   * 开始时间戳
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64"
  )
  public final Long startTimeMs;

  /**
   * 已经开始时间
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64"
  )
  public final Long startPassedMs;

  public GameInfo(Long startTimeMs, Long startPassedMs) {
    this(startTimeMs, startPassedMs, ByteString.EMPTY);
  }

  public GameInfo(Long startTimeMs, Long startPassedMs, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.startTimeMs = startTimeMs;
    this.startPassedMs = startPassedMs;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.startTimeMs = startTimeMs;
    builder.startPassedMs = startPassedMs;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GameInfo)) return false;
    GameInfo o = (GameInfo) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(startTimeMs, o.startTimeMs)
        && Internal.equals(startPassedMs, o.startPassedMs);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (startTimeMs != null ? startTimeMs.hashCode() : 0);
      result = result * 37 + (startPassedMs != null ? startPassedMs.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (startTimeMs != null) builder.append(", startTimeMs=").append(startTimeMs);
    if (startPassedMs != null) builder.append(", startPassedMs=").append(startPassedMs);
    return builder.replace(0, 2, "GameInfo{").append('}').toString();
  }

  public byte[] toByteArray() {
    return GameInfo.ADAPTER.encode(this);
  }

  public static final GameInfo parseFrom(byte[] data) throws IOException {
    GameInfo c = null;
       c = GameInfo.ADAPTER.decode(data);
    return c;
  }

  /**
   * 开始时间戳
   */
  public Long getStartTimeMs() {
    if(startTimeMs==null){
        return DEFAULT_STARTTIMEMS;
    }
    return startTimeMs;
  }

  /**
   * 已经开始时间
   */
  public Long getStartPassedMs() {
    if(startPassedMs==null){
        return DEFAULT_STARTPASSEDMS;
    }
    return startPassedMs;
  }

  /**
   * 开始时间戳
   */
  public boolean hasStartTimeMs() {
    return startTimeMs!=null;
  }

  /**
   * 已经开始时间
   */
  public boolean hasStartPassedMs() {
    return startPassedMs!=null;
  }

  public static final class Builder extends Message.Builder<GameInfo, Builder> {
    public Long startTimeMs;

    public Long startPassedMs;

    public Builder() {
    }

    /**
     * 开始时间戳
     */
    public Builder setStartTimeMs(Long startTimeMs) {
      this.startTimeMs = startTimeMs;
      return this;
    }

    /**
     * 已经开始时间
     */
    public Builder setStartPassedMs(Long startPassedMs) {
      this.startPassedMs = startPassedMs;
      return this;
    }

    @Override
    public GameInfo build() {
      return new GameInfo(startTimeMs, startPassedMs, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GameInfo extends ProtoAdapter<GameInfo> {
    public ProtoAdapter_GameInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, GameInfo.class);
    }

    @Override
    public int encodedSize(GameInfo value) {
      return ProtoAdapter.SINT64.encodedSizeWithTag(1, value.startTimeMs)
          + ProtoAdapter.SINT64.encodedSizeWithTag(2, value.startPassedMs)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GameInfo value) throws IOException {
      ProtoAdapter.SINT64.encodeWithTag(writer, 1, value.startTimeMs);
      ProtoAdapter.SINT64.encodeWithTag(writer, 2, value.startPassedMs);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GameInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setStartTimeMs(ProtoAdapter.SINT64.decode(reader)); break;
          case 2: builder.setStartPassedMs(ProtoAdapter.SINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GameInfo redact(GameInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
