// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: HotChannel.proto
package com.wali.live.proto.HotChannel;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ********************zhibo.recommend.gameSublist*************************************&#42;/
 */
public final class GetGameSublistReq extends Message<GetGameSublistReq, GetGameSublistReq.Builder> {
  public static final ProtoAdapter<GetGameSublistReq> ADAPTER = new ProtoAdapter_GetGameSublistReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UID = 0L;

  public static final Integer DEFAULT_CHANNELID = 0;

  public static final Integer DEFAULT_SUBLISTID = 0;

  public static final Integer DEFAULT_SOURCE = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long uid;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer channelId;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer subListId;

  /**
   * 二级列表基础数据来源[客户端不用关心,需要透传给服务器]
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer source;

  public GetGameSublistReq(Long uid, Integer channelId, Integer subListId, Integer source) {
    this(uid, channelId, subListId, source, ByteString.EMPTY);
  }

  public GetGameSublistReq(Long uid, Integer channelId, Integer subListId, Integer source,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.uid = uid;
    this.channelId = channelId;
    this.subListId = subListId;
    this.source = source;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uid = uid;
    builder.channelId = channelId;
    builder.subListId = subListId;
    builder.source = source;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGameSublistReq)) return false;
    GetGameSublistReq o = (GetGameSublistReq) other;
    return unknownFields().equals(o.unknownFields())
        && uid.equals(o.uid)
        && channelId.equals(o.channelId)
        && subListId.equals(o.subListId)
        && Internal.equals(source, o.source);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + uid.hashCode();
      result = result * 37 + channelId.hashCode();
      result = result * 37 + subListId.hashCode();
      result = result * 37 + (source != null ? source.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", uid=").append(uid);
    builder.append(", channelId=").append(channelId);
    builder.append(", subListId=").append(subListId);
    if (source != null) builder.append(", source=").append(source);
    return builder.replace(0, 2, "GetGameSublistReq{").append('}').toString();
  }

  public byte[] toByteArray() {
    return GetGameSublistReq.ADAPTER.encode(this);
  }

  public static final class Builder extends Message.Builder<GetGameSublistReq, Builder> {
    public Long uid;

    public Integer channelId;

    public Integer subListId;

    public Integer source;

    public Builder() {
    }

    public Builder setUid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder setChannelId(Integer channelId) {
      this.channelId = channelId;
      return this;
    }

    public Builder setSubListId(Integer subListId) {
      this.subListId = subListId;
      return this;
    }

    /**
     * 二级列表基础数据来源[客户端不用关心,需要透传给服务器]
     */
    public Builder setSource(Integer source) {
      this.source = source;
      return this;
    }

    @Override
    public GetGameSublistReq build() {
      if (uid == null
          || channelId == null
          || subListId == null) {
        throw Internal.missingRequiredFields(uid, "uid",
            channelId, "channelId",
            subListId, "subListId");
      }
      return new GetGameSublistReq(uid, channelId, subListId, source, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetGameSublistReq extends ProtoAdapter<GetGameSublistReq> {
    public ProtoAdapter_GetGameSublistReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetGameSublistReq.class);
    }

    @Override
    public int encodedSize(GetGameSublistReq value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.uid)
          + ProtoAdapter.UINT32.encodedSizeWithTag(2, value.channelId)
          + ProtoAdapter.UINT32.encodedSizeWithTag(3, value.subListId)
          + ProtoAdapter.UINT32.encodedSizeWithTag(4, value.source)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetGameSublistReq value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.uid);
      ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.channelId);
      ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.subListId);
      ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.source);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetGameSublistReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setUid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.setChannelId(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.setSubListId(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.setSource(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetGameSublistReq redact(GetGameSublistReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
