// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: User.proto
package com.wali.live.proto.User;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UserEcoAttr extends Message<UserEcoAttr, UserEcoAttr.Builder> {
  public static final ProtoAdapter<UserEcoAttr> ADAPTER = new ProtoAdapter_UserEcoAttr();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_BULLET_GIFT_ID = 0;

  public static final Integer DEFAULT_BULLET_GEM_CNT = 0;

  public static final Integer DEFAULT_CONSUM_VIRTUAL_GEM_CNT = 0;

  public static final Integer DEFAULT_USABLE_VIRTUAL_GEM_CNT = 0;

  /**
   * 收费弹幕礼物ID
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer bullet_gift_id;

  /**
   * 收费弹幕钻石数
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer bullet_gem_cnt;

  /**
   * 消费的虚拟钻石数
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer consum_virtual_gem_cnt;

  /**
   * 可用的虚拟钻石数
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer usable_virtual_gem_cnt;

  public UserEcoAttr(Integer bullet_gift_id, Integer bullet_gem_cnt, Integer consum_virtual_gem_cnt,
      Integer usable_virtual_gem_cnt) {
    this(bullet_gift_id, bullet_gem_cnt, consum_virtual_gem_cnt, usable_virtual_gem_cnt, ByteString.EMPTY);
  }

  public UserEcoAttr(Integer bullet_gift_id, Integer bullet_gem_cnt, Integer consum_virtual_gem_cnt,
      Integer usable_virtual_gem_cnt, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.bullet_gift_id = bullet_gift_id;
    this.bullet_gem_cnt = bullet_gem_cnt;
    this.consum_virtual_gem_cnt = consum_virtual_gem_cnt;
    this.usable_virtual_gem_cnt = usable_virtual_gem_cnt;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.bullet_gift_id = bullet_gift_id;
    builder.bullet_gem_cnt = bullet_gem_cnt;
    builder.consum_virtual_gem_cnt = consum_virtual_gem_cnt;
    builder.usable_virtual_gem_cnt = usable_virtual_gem_cnt;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserEcoAttr)) return false;
    UserEcoAttr o = (UserEcoAttr) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(bullet_gift_id, o.bullet_gift_id)
        && Internal.equals(bullet_gem_cnt, o.bullet_gem_cnt)
        && Internal.equals(consum_virtual_gem_cnt, o.consum_virtual_gem_cnt)
        && Internal.equals(usable_virtual_gem_cnt, o.usable_virtual_gem_cnt);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (bullet_gift_id != null ? bullet_gift_id.hashCode() : 0);
      result = result * 37 + (bullet_gem_cnt != null ? bullet_gem_cnt.hashCode() : 0);
      result = result * 37 + (consum_virtual_gem_cnt != null ? consum_virtual_gem_cnt.hashCode() : 0);
      result = result * 37 + (usable_virtual_gem_cnt != null ? usable_virtual_gem_cnt.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (bullet_gift_id != null) builder.append(", bullet_gift_id=").append(bullet_gift_id);
    if (bullet_gem_cnt != null) builder.append(", bullet_gem_cnt=").append(bullet_gem_cnt);
    if (consum_virtual_gem_cnt != null) builder.append(", consum_virtual_gem_cnt=").append(consum_virtual_gem_cnt);
    if (usable_virtual_gem_cnt != null) builder.append(", usable_virtual_gem_cnt=").append(usable_virtual_gem_cnt);
    return builder.replace(0, 2, "UserEcoAttr{").append('}').toString();
  }

  public byte[] toByteArray() {
    return UserEcoAttr.ADAPTER.encode(this);
  }

  public static final UserEcoAttr parseFrom(byte[] data) throws IOException {
    UserEcoAttr c = null;
       c = UserEcoAttr.ADAPTER.decode(data);
    return c;
  }

  /**
   * 收费弹幕礼物ID
   */
  public Integer getBulletGiftId() {
    if(bullet_gift_id==null){
        return DEFAULT_BULLET_GIFT_ID;
    }
    return bullet_gift_id;
  }

  /**
   * 收费弹幕钻石数
   */
  public Integer getBulletGemCnt() {
    if(bullet_gem_cnt==null){
        return DEFAULT_BULLET_GEM_CNT;
    }
    return bullet_gem_cnt;
  }

  /**
   * 消费的虚拟钻石数
   */
  public Integer getConsumVirtualGemCnt() {
    if(consum_virtual_gem_cnt==null){
        return DEFAULT_CONSUM_VIRTUAL_GEM_CNT;
    }
    return consum_virtual_gem_cnt;
  }

  /**
   * 可用的虚拟钻石数
   */
  public Integer getUsableVirtualGemCnt() {
    if(usable_virtual_gem_cnt==null){
        return DEFAULT_USABLE_VIRTUAL_GEM_CNT;
    }
    return usable_virtual_gem_cnt;
  }

  /**
   * 收费弹幕礼物ID
   */
  public boolean hasBulletGiftId() {
    return bullet_gift_id!=null;
  }

  /**
   * 收费弹幕钻石数
   */
  public boolean hasBulletGemCnt() {
    return bullet_gem_cnt!=null;
  }

  /**
   * 消费的虚拟钻石数
   */
  public boolean hasConsumVirtualGemCnt() {
    return consum_virtual_gem_cnt!=null;
  }

  /**
   * 可用的虚拟钻石数
   */
  public boolean hasUsableVirtualGemCnt() {
    return usable_virtual_gem_cnt!=null;
  }

  public static final class Builder extends Message.Builder<UserEcoAttr, Builder> {
    public Integer bullet_gift_id;

    public Integer bullet_gem_cnt;

    public Integer consum_virtual_gem_cnt;

    public Integer usable_virtual_gem_cnt;

    public Builder() {
    }

    /**
     * 收费弹幕礼物ID
     */
    public Builder setBulletGiftId(Integer bullet_gift_id) {
      this.bullet_gift_id = bullet_gift_id;
      return this;
    }

    /**
     * 收费弹幕钻石数
     */
    public Builder setBulletGemCnt(Integer bullet_gem_cnt) {
      this.bullet_gem_cnt = bullet_gem_cnt;
      return this;
    }

    /**
     * 消费的虚拟钻石数
     */
    public Builder setConsumVirtualGemCnt(Integer consum_virtual_gem_cnt) {
      this.consum_virtual_gem_cnt = consum_virtual_gem_cnt;
      return this;
    }

    /**
     * 可用的虚拟钻石数
     */
    public Builder setUsableVirtualGemCnt(Integer usable_virtual_gem_cnt) {
      this.usable_virtual_gem_cnt = usable_virtual_gem_cnt;
      return this;
    }

    @Override
    public UserEcoAttr build() {
      return new UserEcoAttr(bullet_gift_id, bullet_gem_cnt, consum_virtual_gem_cnt, usable_virtual_gem_cnt, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserEcoAttr extends ProtoAdapter<UserEcoAttr> {
    public ProtoAdapter_UserEcoAttr() {
      super(FieldEncoding.LENGTH_DELIMITED, UserEcoAttr.class);
    }

    @Override
    public int encodedSize(UserEcoAttr value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.bullet_gift_id)
          + ProtoAdapter.UINT32.encodedSizeWithTag(2, value.bullet_gem_cnt)
          + ProtoAdapter.UINT32.encodedSizeWithTag(3, value.consum_virtual_gem_cnt)
          + ProtoAdapter.UINT32.encodedSizeWithTag(4, value.usable_virtual_gem_cnt)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UserEcoAttr value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.bullet_gift_id);
      ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.bullet_gem_cnt);
      ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.consum_virtual_gem_cnt);
      ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.usable_virtual_gem_cnt);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserEcoAttr decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setBulletGiftId(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.setBulletGemCnt(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.setConsumVirtualGemCnt(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.setUsableVirtualGemCnt(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UserEcoAttr redact(UserEcoAttr value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
