// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Notification.proto
package com.zq.live.proto.Notification;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import com.zq.live.proto.Common.UserInfo;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CombineRoomInviteInCreateRoomMsg extends Message<CombineRoomInviteInCreateRoomMsg, CombineRoomInviteInCreateRoomMsg.Builder> {
  public static final ProtoAdapter<CombineRoomInviteInCreateRoomMsg> ADAPTER = new ProtoAdapter_CombineRoomInviteInCreateRoomMsg();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_INVITEMSG = "";

  public static final Integer DEFAULT_ROOMID = 0;

  /**
   * 发起邀请的用户详情
   */
  @WireField(
      tag = 1,
      adapter = "com.zq.live.proto.Common.UserInfo#ADAPTER"
  )
  private final UserInfo user;

  /**
   * 邀请信息
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  private final String inviteMsg;

  /**
   * 房间id
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  private final Integer roomID;

  public CombineRoomInviteInCreateRoomMsg(UserInfo user, String inviteMsg, Integer roomID) {
    this(user, inviteMsg, roomID, ByteString.EMPTY);
  }

  public CombineRoomInviteInCreateRoomMsg(UserInfo user, String inviteMsg, Integer roomID,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.user = user;
    this.inviteMsg = inviteMsg;
    this.roomID = roomID;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.user = user;
    builder.inviteMsg = inviteMsg;
    builder.roomID = roomID;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CombineRoomInviteInCreateRoomMsg)) return false;
    CombineRoomInviteInCreateRoomMsg o = (CombineRoomInviteInCreateRoomMsg) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(user, o.user)
        && Internal.equals(inviteMsg, o.inviteMsg)
        && Internal.equals(roomID, o.roomID);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (user != null ? user.hashCode() : 0);
      result = result * 37 + (inviteMsg != null ? inviteMsg.hashCode() : 0);
      result = result * 37 + (roomID != null ? roomID.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (user != null) builder.append(", user=").append(user);
    if (inviteMsg != null) builder.append(", inviteMsg=").append(inviteMsg);
    if (roomID != null) builder.append(", roomID=").append(roomID);
    return builder.replace(0, 2, "CombineRoomInviteInCreateRoomMsg{").append('}').toString();
  }

  public byte[] toByteArray() {
    return CombineRoomInviteInCreateRoomMsg.ADAPTER.encode(this);
  }

  public static final CombineRoomInviteInCreateRoomMsg parseFrom(byte[] data) throws IOException {
    CombineRoomInviteInCreateRoomMsg c = null;
       c = CombineRoomInviteInCreateRoomMsg.ADAPTER.decode(data);
    return c;
  }

  /**
   * 发起邀请的用户详情
   */
  public UserInfo getUser() {
    if(user==null){
        return new UserInfo.Builder().build();
    }
    return user;
  }

  /**
   * 邀请信息
   */
  public String getInviteMsg() {
    if(inviteMsg==null){
        return DEFAULT_INVITEMSG;
    }
    return inviteMsg;
  }

  /**
   * 房间id
   */
  public Integer getRoomID() {
    if(roomID==null){
        return DEFAULT_ROOMID;
    }
    return roomID;
  }

  /**
   * 发起邀请的用户详情
   */
  public boolean hasUser() {
    return user!=null;
  }

  /**
   * 邀请信息
   */
  public boolean hasInviteMsg() {
    return inviteMsg!=null;
  }

  /**
   * 房间id
   */
  public boolean hasRoomID() {
    return roomID!=null;
  }

  public static final class Builder extends Message.Builder<CombineRoomInviteInCreateRoomMsg, Builder> {
    private UserInfo user;

    private String inviteMsg;

    private Integer roomID;

    public Builder() {
    }

    /**
     * 发起邀请的用户详情
     */
    public Builder setUser(UserInfo user) {
      this.user = user;
      return this;
    }

    /**
     * 邀请信息
     */
    public Builder setInviteMsg(String inviteMsg) {
      this.inviteMsg = inviteMsg;
      return this;
    }

    /**
     * 房间id
     */
    public Builder setRoomID(Integer roomID) {
      this.roomID = roomID;
      return this;
    }

    @Override
    public CombineRoomInviteInCreateRoomMsg build() {
      return new CombineRoomInviteInCreateRoomMsg(user, inviteMsg, roomID, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CombineRoomInviteInCreateRoomMsg extends ProtoAdapter<CombineRoomInviteInCreateRoomMsg> {
    public ProtoAdapter_CombineRoomInviteInCreateRoomMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, CombineRoomInviteInCreateRoomMsg.class);
    }

    @Override
    public int encodedSize(CombineRoomInviteInCreateRoomMsg value) {
      return UserInfo.ADAPTER.encodedSizeWithTag(1, value.user)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.inviteMsg)
          + ProtoAdapter.UINT32.encodedSizeWithTag(3, value.roomID)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CombineRoomInviteInCreateRoomMsg value) throws
        IOException {
      UserInfo.ADAPTER.encodeWithTag(writer, 1, value.user);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.inviteMsg);
      ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.roomID);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CombineRoomInviteInCreateRoomMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setUser(UserInfo.ADAPTER.decode(reader)); break;
          case 2: builder.setInviteMsg(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.setRoomID(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CombineRoomInviteInCreateRoomMsg redact(CombineRoomInviteInCreateRoomMsg value) {
      Builder builder = value.newBuilder();
      if (builder.user != null) builder.user = UserInfo.ADAPTER.redact(builder.user);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
