// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Notification.proto
package com.zq.live.proto.Notification;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * ENotificationMsgType 房间消息类型
 */
public enum ENotificationMsgType implements WireEnum {
  /**
   * 未知消息
   */
  NM_UNKNOWN(0),

  /**
   * 关注类型
   */
  NM_FOLLOW(1),

  /**
   * 一唱到底邀请
   */
  NM_INVITE_STAND(2),

  /**
   * 系统警告
   */
  NM_SYS_WARNING_MSG(3),

  /**
   * 双人房邀请信令
   */
  NM_CR_INVITE(4),

  /**
   * 双人房进房信令
   */
  NM_CR_ENTER(5),

  /**
   * 双人房拒绝邀请信令
   */
  NM_CR_REFUSE(6),

  /**
   * 双人房邀请信令
   */
  NM_CR_INVITEV2(7),

  /**
   * 点赞feed
   */
  NM_FD_LIKE(8),

  /**
   * 点赞评论信令
   */
  NM_FD_COMMENT_LIKE(9),

  /**
   * 添加评论信令
   */
  NM_FD_COMMENT_ADD(10),

  /**
   * 点赞帖子
   */
  NM_PS_LIKE(11),

  /**
   * 点赞帖子评论信令
   */
  NM_PS_COMMENT_LIKE(12),

  /**
   * 添加帖子评论信令
   */
  NM_PS_COMMENT_ADD(13),

  /**
   * 排麦房邀请用户
   */
  NM_INVITE_MIC(14),

  /**
   * 特别关注发帖子的信令
   */
  NM_SPFOLLOW_NEWPOST(15),

  /**
   * 特别关注更新相册的信令
   */
  NM_SPFOLLOW_UPDATEALBUM(16),

  /**
   * 收到礼物的小红点消息
   */
  NM_GIFT_RECEIVES(17);

  public static final ProtoAdapter<ENotificationMsgType> ADAPTER = new ProtoAdapter_ENotificationMsgType();

  private final int value;

  ENotificationMsgType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ENotificationMsgType fromValue(int value) {
    switch (value) {
      case 0: return NM_UNKNOWN;
      case 1: return NM_FOLLOW;
      case 2: return NM_INVITE_STAND;
      case 3: return NM_SYS_WARNING_MSG;
      case 4: return NM_CR_INVITE;
      case 5: return NM_CR_ENTER;
      case 6: return NM_CR_REFUSE;
      case 7: return NM_CR_INVITEV2;
      case 8: return NM_FD_LIKE;
      case 9: return NM_FD_COMMENT_LIKE;
      case 10: return NM_FD_COMMENT_ADD;
      case 11: return NM_PS_LIKE;
      case 12: return NM_PS_COMMENT_LIKE;
      case 13: return NM_PS_COMMENT_ADD;
      case 14: return NM_INVITE_MIC;
      case 15: return NM_SPFOLLOW_NEWPOST;
      case 16: return NM_SPFOLLOW_UPDATEALBUM;
      case 17: return NM_GIFT_RECEIVES;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final class Builder {
    public ENotificationMsgType build() {
      return NM_UNKNOWN;
    }
  }

  private static final class ProtoAdapter_ENotificationMsgType extends EnumAdapter<ENotificationMsgType> {
    ProtoAdapter_ENotificationMsgType() {
      super(ENotificationMsgType.class);
    }

    @Override
    protected ENotificationMsgType fromValue(int value) {
      return ENotificationMsgType.fromValue(value);
    }
  }
}
