// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Relation.proto
package com.wali.live.proto.Relation;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UnFollowResponse extends Message<UnFollowResponse, UnFollowResponse.Builder> {
  public static final ProtoAdapter<UnFollowResponse> ADAPTER = new ProtoAdapter_UnFollowResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_CODE = 0;

  /**
   * 状态码
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer code;

  public UnFollowResponse(Integer code) {
    this(code, ByteString.EMPTY);
  }

  public UnFollowResponse(Integer code, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.code = code;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.code = code;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UnFollowResponse)) return false;
    UnFollowResponse o = (UnFollowResponse) other;
    return unknownFields().equals(o.unknownFields())
        && code.equals(o.code);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + code.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", code=").append(code);
    return builder.replace(0, 2, "UnFollowResponse{").append('}').toString();
  }

  public static final UnFollowResponse parseFrom(byte[] data) throws IOException {
    UnFollowResponse c = null;
       c = UnFollowResponse.ADAPTER.decode(data);
    return c;
  }

  /**
   * 状态码
   */
  public Integer getCode() {
    if(code==null){
        return DEFAULT_CODE;
    }
    return code;
  }

  /**
   * 状态码
   */
  public boolean hasCode() {
    return code!=null;
  }

  public static final class Builder extends Message.Builder<UnFollowResponse, Builder> {
    public Integer code;

    public Builder() {
    }

    /**
     * 状态码
     */
    public Builder setCode(Integer code) {
      this.code = code;
      return this;
    }

    @Override
    public UnFollowResponse build() {
      return new UnFollowResponse(code, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UnFollowResponse extends ProtoAdapter<UnFollowResponse> {
    public ProtoAdapter_UnFollowResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, UnFollowResponse.class);
    }

    @Override
    public int encodedSize(UnFollowResponse value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.code)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UnFollowResponse value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.code);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UnFollowResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setCode(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UnFollowResponse redact(UnFollowResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
