// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: CommonChannel.proto
package com.wali.live.proto.CommonChannel;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * type=103 extData填充内容
 */
public final class VideoLike extends Message<VideoLike, VideoLike.Builder> {
  public static final ProtoAdapter<VideoLike> ADAPTER = new ProtoAdapter_VideoLike();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_BEFCOUNT = 0L;

  /**
   * 点赞前的点赞数
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long befCount;

  public VideoLike(Long befCount) {
    this(befCount, ByteString.EMPTY);
  }

  public VideoLike(Long befCount, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.befCount = befCount;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.befCount = befCount;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoLike)) return false;
    VideoLike o = (VideoLike) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(befCount, o.befCount);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (befCount != null ? befCount.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (befCount != null) builder.append(", befCount=").append(befCount);
    return builder.replace(0, 2, "VideoLike{").append('}').toString();
  }

  public byte[] toByteArray() {
    return VideoLike.ADAPTER.encode(this);
  }

  public static final VideoLike parseFrom(byte[] data) throws IOException {
    VideoLike c = null;
       c = VideoLike.ADAPTER.decode(data);
    return c;
  }

  /**
   * 点赞前的点赞数
   */
  public Long getBefCount() {
    if(befCount==null){
        return DEFAULT_BEFCOUNT;
    }
    return befCount;
  }

  /**
   * 点赞前的点赞数
   */
  public boolean hasBefCount() {
    return befCount!=null;
  }

  public static final class Builder extends Message.Builder<VideoLike, Builder> {
    public Long befCount;

    public Builder() {
    }

    /**
     * 点赞前的点赞数
     */
    public Builder setBefCount(Long befCount) {
      this.befCount = befCount;
      return this;
    }

    @Override
    public VideoLike build() {
      return new VideoLike(befCount, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoLike extends ProtoAdapter<VideoLike> {
    public ProtoAdapter_VideoLike() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoLike.class);
    }

    @Override
    public int encodedSize(VideoLike value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.befCount)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoLike value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.befCount);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoLike decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setBefCount(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoLike redact(VideoLike value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
