// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: relay_room.proto
package com.zq.live.proto.RelayRoom;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class RReqAddMusicMsg extends Message<RReqAddMusicMsg, RReqAddMusicMsg.Builder> {
  public static final ProtoAdapter<RReqAddMusicMsg> ADAPTER = new ProtoAdapter_RReqAddMusicMsg();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.zq.live.proto.RelayRoom.RUserMusicDetail#ADAPTER"
  )
  private final RUserMusicDetail detail;

  public RReqAddMusicMsg(RUserMusicDetail detail) {
    this(detail, ByteString.EMPTY);
  }

  public RReqAddMusicMsg(RUserMusicDetail detail, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.detail = detail;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.detail = detail;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RReqAddMusicMsg)) return false;
    RReqAddMusicMsg o = (RReqAddMusicMsg) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(detail, o.detail);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (detail != null ? detail.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (detail != null) builder.append(", detail=").append(detail);
    return builder.replace(0, 2, "RReqAddMusicMsg{").append('}').toString();
  }

  public byte[] toByteArray() {
    return RReqAddMusicMsg.ADAPTER.encode(this);
  }

  public static final RReqAddMusicMsg parseFrom(byte[] data) throws IOException {
    RReqAddMusicMsg c = null;
       c = RReqAddMusicMsg.ADAPTER.decode(data);
    return c;
  }

  public RUserMusicDetail getDetail() {
    if(detail==null){
        return new RUserMusicDetail.Builder().build();
    }
    return detail;
  }

  public boolean hasDetail() {
    return detail!=null;
  }

  public static final class Builder extends Message.Builder<RReqAddMusicMsg, Builder> {
    private RUserMusicDetail detail;

    public Builder() {
    }

    public Builder setDetail(RUserMusicDetail detail) {
      this.detail = detail;
      return this;
    }

    @Override
    public RReqAddMusicMsg build() {
      return new RReqAddMusicMsg(detail, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RReqAddMusicMsg extends ProtoAdapter<RReqAddMusicMsg> {
    public ProtoAdapter_RReqAddMusicMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, RReqAddMusicMsg.class);
    }

    @Override
    public int encodedSize(RReqAddMusicMsg value) {
      return RUserMusicDetail.ADAPTER.encodedSizeWithTag(1, value.detail)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RReqAddMusicMsg value) throws IOException {
      RUserMusicDetail.ADAPTER.encodeWithTag(writer, 1, value.detail);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RReqAddMusicMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setDetail(RUserMusicDetail.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RReqAddMusicMsg redact(RReqAddMusicMsg value) {
      Builder builder = value.newBuilder();
      if (builder.detail != null) builder.detail = RUserMusicDetail.ADAPTER.redact(builder.detail);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
