// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Room.proto
package com.module.playways.rank.msg.event;

import com.module.playways.rank.msg.BasePushInfo;
import com.module.playways.rank.prepare.model.RoundInfoModel;
import com.zq.live.proto.Room.EQRoundOverReason;
import com.zq.live.proto.Room.EQRoundResultType;
import com.zq.live.proto.Room.QResultInfo;
import com.zq.live.proto.Room.QRoundAndGameOverMsg;

import java.util.List;

public final class QRoundAndGameOverMsgEvent {
    public BasePushInfo info;


    /**
     * 本轮次结束的毫秒时间戳
     */
    public Long roundOverTimeMs;

    /**
     * 退出用户的ID
     */
    public RoundInfoModel roundInfoModel;

    /**
     * 最终结果信息
     */
    //TODO 自定义一个 MODEL 存起来啊
    public List<QResultInfo> resultInfo;

    public QRoundAndGameOverMsgEvent(BasePushInfo info, QRoundAndGameOverMsg qRoundAndGameOverMsg) {
        this.info = info;
        this.roundOverTimeMs = qRoundAndGameOverMsg.getRoundOverTimeMs();
        this.roundInfoModel = RoundInfoModel.parseFromRoundInfo(qRoundAndGameOverMsg.getCurrentRound());
        this.resultInfo = qRoundAndGameOverMsg.getResultInfoList();
    }

    public BasePushInfo getInfo() {
        return info;
    }

    public Long getRoundOverTimeMs() {
        return roundOverTimeMs;
    }

    public RoundInfoModel getRoundInfoModel() {
        return roundInfoModel;
    }

    public List<QResultInfo> getResultInfo() {
        return resultInfo;
    }
}
