package com.wali.live.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table REGION_TW.
 */
public class RegionTw implements java.io.Serializable {

    private Boolean isHot;
    private String Country;
    private String CountryCode;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RegionTw() {
    }

    public RegionTw(Boolean isHot, String Country, String CountryCode) {
        this.isHot = isHot;
        this.Country = Country;
        this.CountryCode = CountryCode;
    }

    public Boolean getIsHot() {
        return isHot;
    }

    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    public String getCountry() {
        return Country;
    }

    public void setCountry(String Country) {
        this.Country = Country;
    }

    public String getCountryCode() {
        return CountryCode;
    }

    public void setCountryCode(String CountryCode) {
        this.CountryCode = CountryCode;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
