// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: party_room.proto
package com.zq.live.proto.PartyRoom;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PNextRoundMsg extends Message<PNextRoundMsg, PNextRoundMsg.Builder> {
  public static final ProtoAdapter<PNextRoundMsg> ADAPTER = new ProtoAdapter_PNextRoundMsg();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ROUNDOVERTIMEMS = 0L;

  /**
   * 本轮次结束的毫秒时间戳
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64"
  )
  private final Long roundOverTimeMs;

  /**
   * 当前结束轮次的信息
   */
  @WireField(
      tag = 2,
      adapter = "com.zq.live.proto.PartyRoom.PRoundInfo#ADAPTER"
  )
  private final PRoundInfo currentRound;

  /**
   * 下个加载轮次的信息
   */
  @WireField(
      tag = 3,
      adapter = "com.zq.live.proto.PartyRoom.PRoundInfo#ADAPTER"
  )
  private final PRoundInfo nextRound;

  public PNextRoundMsg(Long roundOverTimeMs, PRoundInfo currentRound, PRoundInfo nextRound) {
    this(roundOverTimeMs, currentRound, nextRound, ByteString.EMPTY);
  }

  public PNextRoundMsg(Long roundOverTimeMs, PRoundInfo currentRound, PRoundInfo nextRound,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.roundOverTimeMs = roundOverTimeMs;
    this.currentRound = currentRound;
    this.nextRound = nextRound;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.roundOverTimeMs = roundOverTimeMs;
    builder.currentRound = currentRound;
    builder.nextRound = nextRound;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PNextRoundMsg)) return false;
    PNextRoundMsg o = (PNextRoundMsg) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(roundOverTimeMs, o.roundOverTimeMs)
        && Internal.equals(currentRound, o.currentRound)
        && Internal.equals(nextRound, o.nextRound);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (roundOverTimeMs != null ? roundOverTimeMs.hashCode() : 0);
      result = result * 37 + (currentRound != null ? currentRound.hashCode() : 0);
      result = result * 37 + (nextRound != null ? nextRound.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (roundOverTimeMs != null) builder.append(", roundOverTimeMs=").append(roundOverTimeMs);
    if (currentRound != null) builder.append(", currentRound=").append(currentRound);
    if (nextRound != null) builder.append(", nextRound=").append(nextRound);
    return builder.replace(0, 2, "PNextRoundMsg{").append('}').toString();
  }

  public byte[] toByteArray() {
    return PNextRoundMsg.ADAPTER.encode(this);
  }

  public static final PNextRoundMsg parseFrom(byte[] data) throws IOException {
    PNextRoundMsg c = null;
       c = PNextRoundMsg.ADAPTER.decode(data);
    return c;
  }

  /**
   * 本轮次结束的毫秒时间戳
   */
  public Long getRoundOverTimeMs() {
    if(roundOverTimeMs==null){
        return DEFAULT_ROUNDOVERTIMEMS;
    }
    return roundOverTimeMs;
  }

  /**
   * 当前结束轮次的信息
   */
  public PRoundInfo getCurrentRound() {
    if(currentRound==null){
        return new PRoundInfo.Builder().build();
    }
    return currentRound;
  }

  /**
   * 下个加载轮次的信息
   */
  public PRoundInfo getNextRound() {
    if(nextRound==null){
        return new PRoundInfo.Builder().build();
    }
    return nextRound;
  }

  /**
   * 本轮次结束的毫秒时间戳
   */
  public boolean hasRoundOverTimeMs() {
    return roundOverTimeMs!=null;
  }

  /**
   * 当前结束轮次的信息
   */
  public boolean hasCurrentRound() {
    return currentRound!=null;
  }

  /**
   * 下个加载轮次的信息
   */
  public boolean hasNextRound() {
    return nextRound!=null;
  }

  public static final class Builder extends Message.Builder<PNextRoundMsg, Builder> {
    private Long roundOverTimeMs;

    private PRoundInfo currentRound;

    private PRoundInfo nextRound;

    public Builder() {
    }

    /**
     * 本轮次结束的毫秒时间戳
     */
    public Builder setRoundOverTimeMs(Long roundOverTimeMs) {
      this.roundOverTimeMs = roundOverTimeMs;
      return this;
    }

    /**
     * 当前结束轮次的信息
     */
    public Builder setCurrentRound(PRoundInfo currentRound) {
      this.currentRound = currentRound;
      return this;
    }

    /**
     * 下个加载轮次的信息
     */
    public Builder setNextRound(PRoundInfo nextRound) {
      this.nextRound = nextRound;
      return this;
    }

    @Override
    public PNextRoundMsg build() {
      return new PNextRoundMsg(roundOverTimeMs, currentRound, nextRound, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PNextRoundMsg extends ProtoAdapter<PNextRoundMsg> {
    public ProtoAdapter_PNextRoundMsg() {
      super(FieldEncoding.LENGTH_DELIMITED, PNextRoundMsg.class);
    }

    @Override
    public int encodedSize(PNextRoundMsg value) {
      return ProtoAdapter.SINT64.encodedSizeWithTag(1, value.roundOverTimeMs)
          + PRoundInfo.ADAPTER.encodedSizeWithTag(2, value.currentRound)
          + PRoundInfo.ADAPTER.encodedSizeWithTag(3, value.nextRound)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PNextRoundMsg value) throws IOException {
      ProtoAdapter.SINT64.encodeWithTag(writer, 1, value.roundOverTimeMs);
      PRoundInfo.ADAPTER.encodeWithTag(writer, 2, value.currentRound);
      PRoundInfo.ADAPTER.encodeWithTag(writer, 3, value.nextRound);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PNextRoundMsg decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setRoundOverTimeMs(ProtoAdapter.SINT64.decode(reader)); break;
          case 2: builder.setCurrentRound(PRoundInfo.ADAPTER.decode(reader)); break;
          case 3: builder.setNextRound(PRoundInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PNextRoundMsg redact(PNextRoundMsg value) {
      Builder builder = value.newBuilder();
      if (builder.currentRound != null) builder.currentRound = PRoundInfo.ADAPTER.redact(builder.currentRound);
      if (builder.nextRound != null) builder.nextRound = PRoundInfo.ADAPTER.redact(builder.nextRound);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
