// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: race_room.proto
package com.zq.live.proto.RaceRoom;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum ERoundOverType implements WireEnum {
  /**
   * 未知
   */
  EROT_UNKNOWN(0),

  /**
   * 子轮次结束
   */
  EROT_SUB_ROUND_OVER(1),

  /**
   * 主轮次结束
   */
  EROT_MAIN_ROUND_OVER(2);

  public static final ProtoAdapter<ERoundOverType> ADAPTER = new ProtoAdapter_ERoundOverType();

  private final int value;

  ERoundOverType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ERoundOverType fromValue(int value) {
    switch (value) {
      case 0: return EROT_UNKNOWN;
      case 1: return EROT_SUB_ROUND_OVER;
      case 2: return EROT_MAIN_ROUND_OVER;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final class Builder {
    public ERoundOverType build() {
      return EROT_UNKNOWN;
    }
  }

  private static final class ProtoAdapter_ERoundOverType extends EnumAdapter<ERoundOverType> {
    ProtoAdapter_ERoundOverType() {
      super(ERoundOverType.class);
    }

    @Override
    protected ERoundOverType fromValue(int value) {
      return ERoundOverType.fromValue(value);
    }
  }
}
