// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: race_room.proto
package com.zq.live.proto.RaceRoom;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class RaceGameChoices extends Message<RaceGameChoices, RaceGameChoices.Builder> {
  public static final ProtoAdapter<RaceGameChoices> ADAPTER = new ProtoAdapter_RaceGameChoices();

  private static final long serialVersionUID = 0L;

  /**
   * 当前轮次的游戏列表
   */
  @WireField(
      tag = 1,
      adapter = "com.zq.live.proto.RaceRoom.RaceGameInfo#ADAPTER",
      label = WireField.Label.REPEATED
  )
  private final List<RaceGameInfo> games;

  /**
   * 可以报名选择的游戏列表
   */
  @WireField(
      tag = 2,
      adapter = "com.zq.live.proto.RaceRoom.RaceGameInfo#ADAPTER",
      label = WireField.Label.REPEATED
  )
  private final List<RaceGameInfo> couldChoiceGames;

  public RaceGameChoices(List<RaceGameInfo> games, List<RaceGameInfo> couldChoiceGames) {
    this(games, couldChoiceGames, ByteString.EMPTY);
  }

  public RaceGameChoices(List<RaceGameInfo> games, List<RaceGameInfo> couldChoiceGames,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.games = Internal.immutableCopyOf("games", games);
    this.couldChoiceGames = Internal.immutableCopyOf("couldChoiceGames", couldChoiceGames);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.games = Internal.copyOf("games", games);
    builder.couldChoiceGames = Internal.copyOf("couldChoiceGames", couldChoiceGames);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RaceGameChoices)) return false;
    RaceGameChoices o = (RaceGameChoices) other;
    return unknownFields().equals(o.unknownFields())
        && games.equals(o.games)
        && couldChoiceGames.equals(o.couldChoiceGames);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + games.hashCode();
      result = result * 37 + couldChoiceGames.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!games.isEmpty()) builder.append(", games=").append(games);
    if (!couldChoiceGames.isEmpty()) builder.append(", couldChoiceGames=").append(couldChoiceGames);
    return builder.replace(0, 2, "RaceGameChoices{").append('}').toString();
  }

  public byte[] toByteArray() {
    return RaceGameChoices.ADAPTER.encode(this);
  }

  public static final RaceGameChoices parseFrom(byte[] data) throws IOException {
    RaceGameChoices c = null;
       c = RaceGameChoices.ADAPTER.decode(data);
    return c;
  }

  /**
   * 当前轮次的游戏列表
   */
  public List<RaceGameInfo> getGamesList() {
    if(games==null){
        return new java.util.ArrayList<RaceGameInfo>();
    }
    return games;
  }

  /**
   * 可以报名选择的游戏列表
   */
  public List<RaceGameInfo> getCouldChoiceGamesList() {
    if(couldChoiceGames==null){
        return new java.util.ArrayList<RaceGameInfo>();
    }
    return couldChoiceGames;
  }

  /**
   * 当前轮次的游戏列表
   */
  public boolean hasGamesList() {
    return games!=null;
  }

  /**
   * 可以报名选择的游戏列表
   */
  public boolean hasCouldChoiceGamesList() {
    return couldChoiceGames!=null;
  }

  public static final class Builder extends Message.Builder<RaceGameChoices, Builder> {
    private List<RaceGameInfo> games;

    private List<RaceGameInfo> couldChoiceGames;

    public Builder() {
      games = Internal.newMutableList();
      couldChoiceGames = Internal.newMutableList();
    }

    /**
     * 当前轮次的游戏列表
     */
    public Builder addAllGames(List<RaceGameInfo> games) {
      Internal.checkElementsNotNull(games);
      this.games = games;
      return this;
    }

    /**
     * 可以报名选择的游戏列表
     */
    public Builder addAllCouldChoiceGames(List<RaceGameInfo> couldChoiceGames) {
      Internal.checkElementsNotNull(couldChoiceGames);
      this.couldChoiceGames = couldChoiceGames;
      return this;
    }

    @Override
    public RaceGameChoices build() {
      return new RaceGameChoices(games, couldChoiceGames, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RaceGameChoices extends ProtoAdapter<RaceGameChoices> {
    public ProtoAdapter_RaceGameChoices() {
      super(FieldEncoding.LENGTH_DELIMITED, RaceGameChoices.class);
    }

    @Override
    public int encodedSize(RaceGameChoices value) {
      return RaceGameInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.games)
          + RaceGameInfo.ADAPTER.asRepeated().encodedSizeWithTag(2, value.couldChoiceGames)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RaceGameChoices value) throws IOException {
      RaceGameInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.games);
      RaceGameInfo.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.couldChoiceGames);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RaceGameChoices decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.games.add(RaceGameInfo.ADAPTER.decode(reader)); break;
          case 2: builder.couldChoiceGames.add(RaceGameInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RaceGameChoices redact(RaceGameChoices value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.games, RaceGameInfo.ADAPTER);
      Internal.redactElements(builder.couldChoiceGames, RaceGameInfo.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
