// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: LiveShow.proto
package com.wali.live.proto.LiveShow;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class DelBackRsp extends Message<DelBackRsp, DelBackRsp.Builder> {
  public static final ProtoAdapter<DelBackRsp> ADAPTER = new ProtoAdapter_DelBackRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RET = 0;

  public static final Long DEFAULT_UID = 0L;

  /**
   * 返回码
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer ret;

  /**
   * 用户id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long uId;

  public DelBackRsp(Integer ret, Long uId) {
    this(ret, uId, ByteString.EMPTY);
  }

  public DelBackRsp(Integer ret, Long uId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ret = ret;
    this.uId = uId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ret = ret;
    builder.uId = uId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DelBackRsp)) return false;
    DelBackRsp o = (DelBackRsp) other;
    return unknownFields().equals(o.unknownFields())
        && ret.equals(o.ret)
        && Internal.equals(uId, o.uId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + ret.hashCode();
      result = result * 37 + (uId != null ? uId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", ret=").append(ret);
    if (uId != null) builder.append(", uId=").append(uId);
    return builder.replace(0, 2, "DelBackRsp{").append('}').toString();
  }

  public static final DelBackRsp parseFrom(byte[] data) throws IOException {
    DelBackRsp c = null;
       c = DelBackRsp.ADAPTER.decode(data);
    return c;
  }

  /**
   * 返回码
   */
  public Integer getRet() {
    if(ret==null){
        return DEFAULT_RET;
    }
    return ret;
  }

  /**
   * 用户id
   */
  public Long getUId() {
    if(uId==null){
        return DEFAULT_UID;
    }
    return uId;
  }

  /**
   * 返回码
   */
  public boolean hasRet() {
    return ret!=null;
  }

  /**
   * 用户id
   */
  public boolean hasUId() {
    return uId!=null;
  }

  public static final class Builder extends Message.Builder<DelBackRsp, Builder> {
    public Integer ret;

    public Long uId;

    public Builder() {
    }

    /**
     * 返回码
     */
    public Builder setRet(Integer ret) {
      this.ret = ret;
      return this;
    }

    /**
     * 用户id
     */
    public Builder setUId(Long uId) {
      this.uId = uId;
      return this;
    }

    @Override
    public DelBackRsp build() {
      return new DelBackRsp(ret, uId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DelBackRsp extends ProtoAdapter<DelBackRsp> {
    public ProtoAdapter_DelBackRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, DelBackRsp.class);
    }

    @Override
    public int encodedSize(DelBackRsp value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.ret)
          + ProtoAdapter.UINT64.encodedSizeWithTag(2, value.uId)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DelBackRsp value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.ret);
      ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.uId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DelBackRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.setRet(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.setUId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DelBackRsp redact(DelBackRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
